In [1]:
import numpy as np

## Sum

In [19]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [3]:
np.sum(a)

np.int64(210)

In [4]:
filt = a < 5

In [5]:
a[filt]

array([1, 2, 3, 4])

In [6]:
np.sum(filt)

np.int64(4)

In [7]:
np.sum(a[filt])

np.int64(10)

In [8]:
np.sum(a, axis=0)

array([34, 38, 42, 46, 50])

In [9]:
np.sum(a, axis=1)

array([15, 40, 65, 90])

In [10]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## All

In [11]:
a = np.arange(20).reshape(4,5)

In [13]:
filt = a > -1

In [14]:
np.all(filt)

np.True_

In [15]:
np.all(filt, axis=1)

array([ True,  True,  True,  True])

In [16]:
np.all(filt, axis=0)

array([ True,  True,  True,  True,  True])

In [17]:
a > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [18]:
np.all(a>5)

np.False_

## Any

In [20]:
np.any(a>5)

np.True_