In [1]:
import numpy as np

## Belirtilen Bir Elemandan Array Oluşturmak

In [2]:
np.full((4,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [3]:
np.full((4,5), 5.9, dtype="str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

## Ardışık Sayılardan Array Oluşturmak

In [4]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [7]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

## Aralığı Eşit Uzaklıktaki Noktalara Bölme
- Belirtilen [başlangıç, bitiş] değerine göre, başlangıç ve bitişi dahil edecek şekilde, aralığı eşit uzaklıkta noktalara bölme

In [12]:
# Default olarak 50 nokta döndürür
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

### Kaç Parçaya Böleceğini Belirtmek

In [14]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [13]:
np.linspace(1,2, num=3)

array([1. , 1.5, 2. ])

In [10]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [11]:
# Son kısım dahil edilmeyebilir
np.linspace(1,2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [15]:
np.linspace(1.5,4.7,3)

array([1.5, 3.1, 4.7])

## Random Integer'lar ile Array Oluşturmak
- [low,high)

In [2]:
np.random.randint(1,10,(3,4))

array([[2, 4, 2, 7],
       [6, 6, 1, 7],
       [2, 9, 5, 5]], dtype=int32)

In [3]:
np.random.randint(1,10, (3,5,5))

array([[[5, 2, 6, 5, 2],
        [8, 1, 2, 8, 8],
        [1, 7, 6, 9, 9],
        [7, 6, 3, 3, 4],
        [5, 4, 6, 8, 1]],

       [[7, 3, 9, 2, 7],
        [6, 5, 1, 5, 6],
        [9, 6, 3, 9, 4],
        [2, 7, 4, 3, 7],
        [3, 2, 2, 2, 5]],

       [[2, 6, 7, 7, 6],
        [9, 7, 2, 7, 6],
        [9, 7, 4, 5, 9],
        [5, 9, 1, 1, 8],
        [6, 6, 6, 4, 6]]], dtype=int32)

## Identity (birim) Matrix Oluşturma
- [low, high)

In [4]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [5]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])