In [1]:
import numpy as np

## Array İşlemleri

### Toplama, çarpma işlemleri

In [2]:
[2,4,8] * 3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [3]:
[2,4,8] + [2,4,8] + [2,4,8]

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [4]:
#Eleman sayıları aynı olmalıdır
x = np.array([1,2,3])
y= np.array([2,4,8])

x*y

array([ 2,  8, 24])

In [5]:
x + y

array([ 3,  6, 11])

In [6]:
3 * x

array([3, 6, 9])

In [7]:
x


array([1, 2, 3])

In [8]:
x = x *3

In [9]:
x

array([3, 6, 9])

### Shape

In [10]:
x = np.zeros((2,3))

In [11]:
y = np.zeros((2,5,4))

In [12]:
x.shape

(2, 3)

In [13]:
y.shape

(2, 5, 4)

### ndim

In [14]:
x.ndim

2

In [15]:
y.ndim

3

### Size

In [16]:
x.size

6

In [17]:
y.size

40

### Dtype

In [18]:
x.dtype

dtype('float64')

In [19]:
y.dtype

dtype('float64')

### Reshaping
- Reshape yapacağınız yapının yaptıktan sonraki yapıpyla aynı eleman sayısına sahip olması lazım.
- Yani size'ları aynı olacak

In [2]:
a = np.arange(1,11)

In [3]:
a.size

10

In [4]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

#### -1 yazılınca boyut otomatik belirlenir

In [6]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Yeni Boyut Eklemek

In [7]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [8]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [9]:
a[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [10]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

### Concatenation

In [11]:
a = np.array([1,2,3,4])

In [12]:
b = np.array([5,6,7,8])

In [13]:
# a veya b güncellenmez
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

- python listlerini de numpy arraylari ile concatenation'ın yapabiliriz

In [14]:
l = [10,11]

In [15]:
np.concatenate([a,b,l]) 


array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [16]:
l = [10,11,12.1]

In [17]:
np.concatenate([a,b,l]) 

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 12.1])

In [18]:
l = [10,11,"12.1"]

In [19]:
np.concatenate([a,b,l]) 

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '12.1'],
      dtype='<U21')

In [20]:
l = (10,11)

In [21]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

### Size Mismatch

In [22]:
a

array([1, 2, 3, 4])

In [24]:
x = np.array([[1,2,3], [4,5,6]])

In [25]:
#(!!!4,1 yazmadı)
a.shape

(4,)

In [26]:
x.shape

(2, 3)

In [28]:
# shape mismatch
np.concatenate([x,a]) 

In [29]:
# Default olarak axis = 0 alır
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
np.concatenate([x,x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Stack

In [45]:
a = np.array([1,2,3,4])
b = np. array([5,6,7,8])

In [50]:
a.shape

(4,)

In [47]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
np.stack([a,b], axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [49]:
np.stack([a,b]).shape

(2, 4)

## Sorting

In [2]:
a = np.array([20, 32, 5, 30, 10])

In [3]:
#Güncellenmez
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [4]:
a

array([20, 32,  5, 30, 10])

In [5]:
#Güncellenir
a.sort()

In [6]:
a

array([ 5, 10, 20, 30, 32])