In [3]:
import numpy as np

## Splitting

In [1]:
l = [10, 20, 30, 40, 50, 60, 70, 80]

In [4]:
np.split (l, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [6]:
a = np. array([10, 20, 30, 40, 50, 60, 70, 80])

In [7]:
np.split(a, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

### Split'in sonucunu birden çok değişkene eşitleme

In [8]:
x,y,z = np.split(l, [2,6])

In [9]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


### vsplit

In [12]:
a = np.arange(20).reshape(2,10)

In [13]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [14]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [15]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### hsplit

In [16]:
a = np.arange(20).reshape(2,10)

In [17]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [18]:
np.hsplit(a, [2])[0]

array([[ 0,  1],
       [10, 11]])

In [19]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [20]:
np.hsplit(a, [2])[0].shape

(2, 2)

In [21]:
np.hsplit(a, [2])[1].shape

(2, 8)

In [22]:
x,y,z = np.hsplit(a, [2,4])

In [23]:
print(x)

[[ 0  1]
 [10 11]]


In [24]:
print(y)

[[ 2  3]
 [12 13]]


In [25]:
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]
