In [1]:
import numpy as np

## Multidimensional Arraylerin Elemanlarına Ulaşmak

In [2]:
a = np.arange(1,21).reshape(4,5) 

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
a[1]

array([ 6,  7,  8,  9, 10])

In [9]:
a[3][4]

np.int64(20)

In [11]:
a[3,4]

np.int64(20)

In [12]:
a[1,1] = 100

In [13]:
a

array([[  1,   2,   3,   4,   5],
       [  6, 100,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [14]:
# Array'in veri tipi neyse ona cast olur, array'in veri tipini dönüştümez
a[1,1] = 100.10
a

array([[  1,   2,   3,   4,   5],
       [  6, 100,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [15]:
a[1,1] = "30"
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Slice Indexing

In [16]:
a = np.arange(1,21).reshape(4,5) 

In [17]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [22]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [23]:
a[:,3]

array([ 4,  9, 14, 19])

## Fancy Indexing

In [28]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
idxs = [4,5,7,11]

In [30]:
#4,5,7 ve 11 idexteki elemanları döndürür
x[idxs]

array([ 5,  6,  8, 12])

In [31]:
a = np.arange(12).reshape(3,4)
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a[0:2,1]

array([1, 5])