In [1]:
import numpy as np

## Subarray

In [2]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [3]:
b = a[:2, :3]
b

array([[1, 2, 3],
       [6, 7, 8]])

In [4]:
b[0,0] = 100

In [5]:
b


array([[100,   2,   3],
       [  6,   7,   8]])

In [6]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

### Copy

In [7]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
b = a[:2,:3].copy()
b

array([[1, 2, 3],
       [6, 7, 8]])

In [9]:
b[0,0] = 100
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [10]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])