In [1]:
import numpy as np

## Conditional Indexing

In [2]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [4]:
a[a<5]

array([1, 2, 3, 4])

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
filt = a < 3

In [7]:
a[filt]

array([1, 2])

In [9]:
b = np.array([2,3,3,4,5,61,7,8,11])
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [10]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [11]:
a[a==b]

array([3, 4, 5, 7, 8])

In [12]:
b[b==a]

array([3, 4, 5, 7, 8])

In [14]:
filt = (a<3) | (a>5)

In [15]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [21]:
filt = (a>3) & (a<=5)

In [22]:
a[filt]

array([4, 5])

### Multidimensional Array'lerde Conditional Indexing

In [23]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [25]:
a<7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [26]:
a = np.array([1,2,3, None])

In [28]:
a == None

array([False, False, False,  True])

In [29]:
a[a==None]

array([None], dtype=object)